name: zstd-w-test
run-name: zstd-w-test
on: [push]
permissions:
  contents: write
env:
  RUNNER_DEBUG: "1"
  ACTIONS_STEP_DEBUG: true
jobs:
  update-release:
    runs-on: windows-latest
    steps:
      - run: |
          openssl --help
      - name: pull-code
        uses: actions/checkout@v4
        with:
          repository: "index-tts/index-tts"
          path: abc
      - run: |
          ls
      - name: pull-code
        uses: wszgrcy/actions-pkg@1.3.1
        with:
          dir: abc
          password: "pass:${{env.PKG_PASSWORD}}"
      - run: |
          ls
      - name: Release
        uses: softprops/action-gh-release@v2.4.0
        with:
          files: 
            '*.enc'
          tag_name: '1.0.0'
          repository: ${{secrets.UPDATE_SHB_PY_REPO}}
          token: ${{ secrets.SHB_PY_TOKEN }}
