name: zstd-w-test
run-name: zstd-w-test
on: [push]
permissions:
  contents: write
env:
  RUNNER_DEBUG: '1'
  ACTIONS_STEP_DEBUG: true
jobs:
  update-release:
    runs-on: windows-latest
    steps:
      - run: |
          # ls
          bash
          ls /
          openssl --help
      - name: pull-code
        uses: wszgrcy/actions-pkg@1.3.0
        
